name: UnlimitedNameTags
version: '${version}'
main: org.alexdev.unlimitednametags.UnlimitedNameTags
api-version: '1.19'
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
