name: UnlimitedNameTags
version: '${version}'
main: org.alexdev.unlimitednametags.UnlimitedNameTags
api-version: '1.19'
author: AlexDev_
folia-supported: true
libraries:
  - de.exlll:configlib-yaml:${configlibVersion}
  - de.exlll:configlib-paper:${configlibVersion}
depend:
  - packetevents
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
  - Oraxen
